economy:
  currencies:
    COINS:
      enabled: true
      symbol: "$"
      decimals: 2
      default-balance: 0.00

    ODRYS:
      enabled: true
      symbol: "Odrys"
      decimals: 2
      default-balance: 0.00

  formatting:
    coins: "%symbol%%amount%"
    odrys: "%amount% %symbol%"

  safety:
    allow-negative-balances: false

  transaction-log:
    enabled: true