profile:
  autosave:
    enabled: true
    interval-ticks: 6000 # 5 minutos
  cache:
    remove-on-quit: true
experience:
  formula:
    base: 100
    multiplier: 1.35
    max-level: 300

  messages:
    level-up: "<gradient:#FACC15:#F97316><bold>¡Subiste al nivel %level%!</bold></gradient>"
    experience-added: "&aHas recibido &e%amount% XP&a."