protection:
  bypass-permission: "ariatusprotection.bypass"

  messages:
    break-blocked: "&cNo puedes romper bloques en esta zona."
    place-blocked: "&cNo puedes colocar bloques en esta zona."
    interact-blocked: "&cEste bloque es decorativo."
    inventory-blocked: "&cNo puedes abrir este bloque."
  worlds:
    ariath:
      enabled: true
      block-breaking: false
      block-placing: false
      blocked-interactions:
        - HOPPER
      blocked-inventory-open:
        - CHEST
        - TRAPPED_CHEST
        - BARREL
        - HOPPER
        - DISPENSER
        - DROPPER
        - FURNACE
        - BLAST_FURNACE
        - SMOKER
        - BREWING_STAND
        - BEACON
        - LECTERN
        - CRAFTING_TABLE
        - STONECUTTER
        - CARTOGRAPHY_TABLE
        - SMITHING_TABLE
        - GRINDSTONE
        - LOOM
        - ANVIL
        - CHIPPED_ANVIL
        - DAMAGED_ANVIL
        - ENCHANTING_TABLE
        - CHISELED_BOOKSHELF
        - DECORATED_POT
      allowed-interactions:
        - CRAFTING_TABLE
        - ENCHANTING_TABLE
        - ANVIL